import { Member, Task, Project, Empresa, EmpresaExtra } from "@/types";

export const DEFAULT_EMPRESAS_DATA: Record<string, EmpresaExtra> = {
  e1: {
    website: "https://techventures.com.br",
    cnpj: "12.345.678/0001-90",
    telefone: "(11) 9 9999-8888",
    endereco: "Av. Paulista, 1000 - São Paulo, SP",
    notas: [
      { id: "n1", title: "Reunião Q1 2025", content: "Discutir metas e KPIs do primeiro trimestre. Foco em crescimento da base de clientes e redução do churn.", createdAt: "2025-01-15", color: "#4361EE" },
      { id: "n2", title: "Roadmap do produto", content: "Prioridades: autenticação OAuth, dashboard de analytics, integração com CRM externo.", createdAt: "2025-02-01", color: "#7C3AED" },
      { id: "n3", title: "Contato investidor", content: "Reunião agendada com fundo de investimento Série A. Preparar deck atualizado.", createdAt: "2025-02-20", color: "#059669" },
    ],
    logins: [
      { id: "l1", service: "AWS Console", username: "admin@techventures.com.br", password: "TV@2025#AWS!", url: "https://console.aws.amazon.com" },
      { id: "l2", service: "GitHub", username: "techventures-org", password: "ghp_xxxxxxxxxxxx", url: "https://github.com/techventures" },
      { id: "l3", service: "Vercel", username: "deploy@techventures.com.br", password: "Vrc!2025@deploy", url: "https://vercel.com/techventures" },
    ],
    ideias: [
      { id: "i1", title: "App mobile nativo", description: "Desenvolver versão mobile do painel financeiro para iOS e Android", votes: 5, createdAt: "2025-01-20", status: "em_avaliacao" },
      { id: "i2", title: "Parceria com FinanceFlow", description: "Explorar sinergia entre os produtos das duas empresas do grupo", votes: 3, createdAt: "2025-02-10", status: "nova" },
      { id: "i3", title: "White-label para bancos", description: "Adaptar a plataforma para ser vendida como white-label para bancos regionais", votes: 7, createdAt: "2025-02-25", status: "aprovada" },
    ],
    faturamento: [
      { id: "f1", month: "2025-01", receita: 45000, despesas: 28000, descricao: "Janeiro — Início do trimestre" },
      { id: "f2", month: "2025-02", receita: 52000, despesas: 31000, descricao: "Fevereiro — Novos clientes" },
      { id: "f3", month: "2025-03", receita: 58000, despesas: 33000, descricao: "Março — Crescimento acelerado" },
    ],
  },
  e2: {
    website: "https://brandstudio.design",
    cnpj: "98.765.432/0001-10",
    telefone: "(11) 3 3333-4444",
    endereco: "Rua Oscar Freire, 500 - São Paulo, SP",
    notas: [
      { id: "n1", title: "Briefing Rebranding", content: "Cliente solicitou atualização completa da identidade visual. Prazo: final de março.", createdAt: "2025-01-10", color: "#DB2777" },
    ],
    logins: [
      { id: "l1", service: "Figma Teams", username: "team@brandstudio.design", password: "Fg!BrandS2025", url: "https://figma.com" },
    ],
    ideias: [
      { id: "i1", title: "Portfólio interativo 3D", description: "Site com apresentação 3D dos projetos de branding", votes: 4, createdAt: "2025-01-15", status: "em_avaliacao" },
    ],
    faturamento: [
      { id: "f1", month: "2025-01", receita: 32000, despesas: 18000, descricao: "Janeiro" },
      { id: "f2", month: "2025-02", receita: 38000, despesas: 21000, descricao: "Fevereiro" },
    ],
  },
  e3: {
    website: "https://financeflow.com.br",
    cnpj: "11.222.333/0001-44",
    telefone: "(21) 2 2222-3333",
    endereco: "Av. Rio Branco, 200 - Rio de Janeiro, RJ",
    notas: [],
    logins: [],
    ideias: [],
    faturamento: [
      { id: "f1", month: "2025-01", receita: 120000, despesas: 75000, descricao: "Janeiro — Gestão de carteiras" },
      { id: "f2", month: "2025-02", receita: 135000, despesas: 82000, descricao: "Fevereiro" },
    ],
  },
  e4: {
    website: "",
    cnpj: "",
    telefone: "(11) 9 8888-7777",
    endereco: "Av. Engenheiro Luís Carlos Berrini, 300 - SP",
    notas: [
      { id: "n1", title: "Fase de formação", content: "Empresa ainda em processo de abertura. CNPJ em análise na Receita Federal.", createdAt: "2025-02-01", color: "#D97706" },
    ],
    logins: [],
    ideias: [
      { id: "i1", title: "Plataforma de aluguel inteligente", description: "IA para sugerir imóveis com base no perfil do usuário", votes: 8, createdAt: "2025-02-05", status: "aprovada" },
    ],
    faturamento: [],
  },
};

export const MEMBERS: Member[] = [
  { id: "m1", name: "Rafael Costa", avatar: "", color: "#4361EE", initials: "RC" },
  { id: "m2", name: "Ana Lima", avatar: "", color: "#7C3AED", initials: "AL" },
  { id: "m3", name: "Lucas Souza", avatar: "", color: "#059669", initials: "LS" },
  { id: "m4", name: "Mariana Reis", avatar: "", color: "#DB2777", initials: "MR" },
  { id: "m5", name: "Pedro Alves", avatar: "", color: "#D97706", initials: "PA" },
];

export const EMPRESAS: Empresa[] = [
  {
    id: "e1",
    name: "TechVentures",
    description: "Holding de empresas de tecnologia e inovação",
    segment: "Tecnologia",
    status: "ativa",
    color: "#4361EE",
    responsible: MEMBERS[0],
    projectCount: 8,
    logo: "",
    initials: "TV",
  },
  {
    id: "e2",
    name: "BrandStudio",
    description: "Agência de branding e identidade visual",
    segment: "Marketing",
    status: "ativa",
    color: "#7C3AED",
    responsible: MEMBERS[1],
    projectCount: 5,
    logo: "",
    initials: "BS",
  },
  {
    id: "e3",
    name: "FinanceFlow",
    description: "Soluções financeiras e gestão de patrimônio",
    segment: "Financeiro",
    status: "ativa",
    color: "#059669",
    responsible: MEMBERS[2],
    projectCount: 3,
    logo: "",
    initials: "FF",
  },
  {
    id: "e4",
    name: "PropTech Imóveis",
    description: "Tecnologia aplicada ao mercado imobiliário",
    segment: "Imobiliário",
    status: "em_formacao",
    color: "#D97706",
    responsible: MEMBERS[4],
    projectCount: 2,
    logo: "",
    initials: "PT",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    empresaId: "e1",
    name: "Painel Financeiro",
    description: "Dashboard centralizado para controle financeiro das empresas",
    status: "active",
    priority: "high",
    progress: 65,
    deadline: "2025-04-15",
    members: [MEMBERS[0], MEMBERS[1]],
    tags: ["SaaS", "Financeiro"],
    taskCount: 12,
    color: "#4361EE",
    icon: "📊",
  },
  {
    id: "p2",
    empresaId: "e1",
    name: "Sistema de Clientes",
    description: "CRM interno para gestão de clientes e leads",
    status: "active",
    priority: "medium",
    progress: 40,
    deadline: "2025-05-30",
    members: [MEMBERS[1], MEMBERS[2]],
    tags: ["CRM", "Produto"],
    taskCount: 9,
    color: "#7C3AED",
    icon: "👥",
  },
  {
    id: "p3",
    empresaId: "e2",
    name: "Rebranding Visual",
    description: "Atualização completa da identidade visual e guidelines",
    status: "active",
    priority: "medium",
    progress: 80,
    deadline: "2025-03-31",
    members: [MEMBERS[1], MEMBERS[3]],
    tags: ["Design", "Branding"],
    taskCount: 6,
    color: "#DB2777",
    icon: "🎨",
  },
  {
    id: "p4",
    empresaId: "e3",
    name: "Automação Fiscal",
    description: "Integração com sistemas de emissão de notas e relatórios fiscais",
    status: "paused",
    priority: "high",
    progress: 25,
    deadline: "2025-06-15",
    members: [MEMBERS[2], MEMBERS[4]],
    tags: ["Financeiro", "Integração"],
    taskCount: 15,
    color: "#059669",
    icon: "📋",
  },
];

export const TASKS: Task[] = [
  // TO DO
  {
    id: "t1",
    projectId: "p1",
    title: "Definir lista de KPIs do Q2",
    description: "Mapear e documentar todos os indicadores financeiros para o segundo trimestre",
    status: "todo",
    priority: "medium",
    category: "Estratégia",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[1]],
    createdAt: "2025-02-01",
    dueDate: "2025-03-10",
    tags: ["SaaS"],
  },
  {
    id: "t2",
    projectId: "p1",
    title: "Configurar schema do banco de dados",
    description: "Criar e revisar estrutura de tabelas para o painel financeiro",
    status: "todo",
    priority: "high",
    category: "Desenvolvimento",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[2]],
    createdAt: "2025-02-03",
    dueDate: "2025-03-12",
    tags: ["SaaS"],
  },
  {
    id: "t3",
    projectId: "p1",
    title: "Confirmar fontes de dados financeiros",
    description: "Validar e documentar todas as fontes de dados para integração",
    status: "todo",
    priority: "medium",
    category: "Financeiro",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[1], MEMBERS[3]],
    createdAt: "2025-02-05",
    dueDate: "2025-03-14",
    tags: ["SaaS"],
  },
  // IN PROGRESS
  {
    id: "t4",
    projectId: "p1",
    title: "Criar visualizações de gráficos",
    description: "Desenvolver componentes de gráficos interativos para o dashboard",
    status: "in_progress",
    priority: "medium",
    category: "Desenvolvimento",
    comments: 12,
    attachments: 2,
    daysLeft: 6,
    progress: 8,
    progressTotal: 15,
    members: [MEMBERS[0], MEMBERS[2]],
    createdAt: "2025-02-08",
    dueDate: "2025-03-18",
    tags: ["SaaS"],
  },
  {
    id: "t5",
    projectId: "p2",
    title: "Construir índice de métricas",
    description: "Indexar e catalogar todas as métricas disponíveis no sistema",
    status: "in_progress",
    priority: "high",
    category: "Produtos",
    comments: 7,
    attachments: 1,
    daysLeft: 3,
    progress: 11,
    progressTotal: 18,
    members: [MEMBERS[1], MEMBERS[4]],
    createdAt: "2025-02-10",
    dueDate: "2025-03-16",
    tags: ["Produto"],
  },
  {
    id: "t6",
    projectId: "p2",
    title: "Revisar fluxo de onboarding",
    description: "Analisar e otimizar o processo de cadastro de novos clientes",
    status: "in_progress",
    priority: "medium",
    category: "Operacional",
    comments: 5,
    attachments: 4,
    daysLeft: 8,
    progress: 6,
    progressTotal: 12,
    members: [MEMBERS[2], MEMBERS[3]],
    createdAt: "2025-02-12",
    dueDate: "2025-03-20",
    tags: ["CRM"],
  },
  // REVIEW
  {
    id: "t7",
    projectId: "p3",
    title: "Validar identidade visual",
    description: "Revisar e aprovar todas as peças do rebranding",
    status: "review",
    priority: "high",
    category: "Marketing",
    comments: 24,
    attachments: 12,
    daysLeft: 2,
    progress: 18,
    progressTotal: 20,
    members: [MEMBERS[1], MEMBERS[3]],
    createdAt: "2025-01-20",
    dueDate: "2025-03-08",
    tags: ["Design"],
  },
  {
    id: "t8",
    projectId: "p1",
    title: "Auditoria de acessos e permissões",
    description: "Revisar e documentar todos os acessos ao sistema financeiro",
    status: "review",
    priority: "medium",
    category: "Administrativo",
    comments: 9,
    attachments: 2,
    daysLeft: 5,
    progress: 15,
    progressTotal: 16,
    members: [MEMBERS[0], MEMBERS[4]],
    createdAt: "2025-01-25",
    dueDate: "2025-03-11",
    tags: ["Segurança"],
  },
  // DONE
  {
    id: "t9",
    projectId: "p3",
    title: "Definir paleta de cores",
    description: "Selecionar e documentar cores primárias e secundárias do rebranding",
    status: "done",
    priority: "medium",
    category: "Marketing",
    comments: 31,
    attachments: 6,
    daysLeft: 0,
    progress: 10,
    progressTotal: 10,
    members: [MEMBERS[1]],
    createdAt: "2025-01-10",
    dueDate: "2025-02-15",
    tags: ["Design"],
  },
  {
    id: "t10",
    projectId: "p1",
    title: "Estruturar organização das empresas",
    description: "Criar hierarquia e estrutura de dados para múltiplas empresas",
    status: "done",
    priority: "high",
    category: "Administrativo",
    comments: 14,
    attachments: 5,
    daysLeft: 0,
    progress: 20,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[2], MEMBERS[4]],
    createdAt: "2025-01-05",
    dueDate: "2025-02-01",
    tags: ["SaaS"],
  },
];
