import { Member, Task, Project, Empresa } from "@/types";

export const MEMBERS: Member[] = [
  { id: "m1", name: "Rafael Costa", avatar: "", color: "#4361EE", initials: "RC" },
  { id: "m2", name: "Ana Lima", avatar: "", color: "#7C3AED", initials: "AL" },
  { id: "m3", name: "Lucas Souza", avatar: "", color: "#059669", initials: "LS" },
  { id: "m4", name: "Mariana Reis", avatar: "", color: "#DB2777", initials: "MR" },
  { id: "m5", name: "Pedro Alves", avatar: "", color: "#D97706", initials: "PA" },
];

export const EMPRESAS: Empresa[] = [
  {
    id: "e1",
    name: "TechVentures",
    description: "Holding de empresas de tecnologia e inovação",
    segment: "Tecnologia",
    status: "ativa",
    color: "#4361EE",
    responsible: MEMBERS[0],
    projectCount: 8,
    logo: "",
    initials: "TV",
  },
  {
    id: "e2",
    name: "BrandStudio",
    description: "Agência de branding e identidade visual",
    segment: "Marketing",
    status: "ativa",
    color: "#7C3AED",
    responsible: MEMBERS[1],
    projectCount: 5,
    logo: "",
    initials: "BS",
  },
  {
    id: "e3",
    name: "FinanceFlow",
    description: "Soluções financeiras e gestão de patrimônio",
    segment: "Financeiro",
    status: "ativa",
    color: "#059669",
    responsible: MEMBERS[2],
    projectCount: 3,
    logo: "",
    initials: "FF",
  },
  {
    id: "e4",
    name: "PropTech Imóveis",
    description: "Tecnologia aplicada ao mercado imobiliário",
    segment: "Imobiliário",
    status: "em_formacao",
    color: "#D97706",
    responsible: MEMBERS[4],
    projectCount: 2,
    logo: "",
    initials: "PT",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "p1",
    empresaId: "e1",
    name: "Painel Financeiro",
    description: "Dashboard centralizado para controle financeiro das empresas",
    status: "active",
    priority: "high",
    progress: 65,
    deadline: "2025-04-15",
    members: [MEMBERS[0], MEMBERS[1]],
    tags: ["SaaS", "Financeiro"],
    taskCount: 12,
    color: "#4361EE",
    icon: "📊",
  },
  {
    id: "p2",
    empresaId: "e1",
    name: "Sistema de Clientes",
    description: "CRM interno para gestão de clientes e leads",
    status: "active",
    priority: "medium",
    progress: 40,
    deadline: "2025-05-30",
    members: [MEMBERS[1], MEMBERS[2]],
    tags: ["CRM", "Produto"],
    taskCount: 9,
    color: "#7C3AED",
    icon: "👥",
  },
  {
    id: "p3",
    empresaId: "e2",
    name: "Rebranding Visual",
    description: "Atualização completa da identidade visual e guidelines",
    status: "active",
    priority: "medium",
    progress: 80,
    deadline: "2025-03-31",
    members: [MEMBERS[1], MEMBERS[3]],
    tags: ["Design", "Branding"],
    taskCount: 6,
    color: "#DB2777",
    icon: "🎨",
  },
  {
    id: "p4",
    empresaId: "e3",
    name: "Automação Fiscal",
    description: "Integração com sistemas de emissão de notas e relatórios fiscais",
    status: "paused",
    priority: "high",
    progress: 25,
    deadline: "2025-06-15",
    members: [MEMBERS[2], MEMBERS[4]],
    tags: ["Financeiro", "Integração"],
    taskCount: 15,
    color: "#059669",
    icon: "📋",
  },
];

export const TASKS: Task[] = [
  // TO DO
  {
    id: "t1",
    projectId: "p1",
    title: "Definir lista de KPIs do Q2",
    description: "Mapear e documentar todos os indicadores financeiros para o segundo trimestre",
    status: "todo",
    priority: "medium",
    category: "Estratégia",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[1]],
    createdAt: "2025-02-01",
    dueDate: "2025-03-10",
    tags: ["SaaS"],
  },
  {
    id: "t2",
    projectId: "p1",
    title: "Configurar schema do banco de dados",
    description: "Criar e revisar estrutura de tabelas para o painel financeiro",
    status: "todo",
    priority: "high",
    category: "Desenvolvimento",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[2]],
    createdAt: "2025-02-03",
    dueDate: "2025-03-12",
    tags: ["SaaS"],
  },
  {
    id: "t3",
    projectId: "p1",
    title: "Confirmar fontes de dados financeiros",
    description: "Validar e documentar todas as fontes de dados para integração",
    status: "todo",
    priority: "medium",
    category: "Financeiro",
    comments: 18,
    attachments: 3,
    daysLeft: 4,
    progress: 14,
    progressTotal: 20,
    members: [MEMBERS[1], MEMBERS[3]],
    createdAt: "2025-02-05",
    dueDate: "2025-03-14",
    tags: ["SaaS"],
  },
  // IN PROGRESS
  {
    id: "t4",
    projectId: "p1",
    title: "Criar visualizações de gráficos",
    description: "Desenvolver componentes de gráficos interativos para o dashboard",
    status: "in_progress",
    priority: "medium",
    category: "Desenvolvimento",
    comments: 12,
    attachments: 2,
    daysLeft: 6,
    progress: 8,
    progressTotal: 15,
    members: [MEMBERS[0], MEMBERS[2]],
    createdAt: "2025-02-08",
    dueDate: "2025-03-18",
    tags: ["SaaS"],
  },
  {
    id: "t5",
    projectId: "p2",
    title: "Construir índice de métricas",
    description: "Indexar e catalogar todas as métricas disponíveis no sistema",
    status: "in_progress",
    priority: "high",
    category: "Produtos",
    comments: 7,
    attachments: 1,
    daysLeft: 3,
    progress: 11,
    progressTotal: 18,
    members: [MEMBERS[1], MEMBERS[4]],
    createdAt: "2025-02-10",
    dueDate: "2025-03-16",
    tags: ["Produto"],
  },
  {
    id: "t6",
    projectId: "p2",
    title: "Revisar fluxo de onboarding",
    description: "Analisar e otimizar o processo de cadastro de novos clientes",
    status: "in_progress",
    priority: "medium",
    category: "Operacional",
    comments: 5,
    attachments: 4,
    daysLeft: 8,
    progress: 6,
    progressTotal: 12,
    members: [MEMBERS[2], MEMBERS[3]],
    createdAt: "2025-02-12",
    dueDate: "2025-03-20",
    tags: ["CRM"],
  },
  // REVIEW
  {
    id: "t7",
    projectId: "p3",
    title: "Validar identidade visual",
    description: "Revisar e aprovar todas as peças do rebranding",
    status: "review",
    priority: "high",
    category: "Marketing",
    comments: 24,
    attachments: 12,
    daysLeft: 2,
    progress: 18,
    progressTotal: 20,
    members: [MEMBERS[1], MEMBERS[3]],
    createdAt: "2025-01-20",
    dueDate: "2025-03-08",
    tags: ["Design"],
  },
  {
    id: "t8",
    projectId: "p1",
    title: "Auditoria de acessos e permissões",
    description: "Revisar e documentar todos os acessos ao sistema financeiro",
    status: "review",
    priority: "medium",
    category: "Administrativo",
    comments: 9,
    attachments: 2,
    daysLeft: 5,
    progress: 15,
    progressTotal: 16,
    members: [MEMBERS[0], MEMBERS[4]],
    createdAt: "2025-01-25",
    dueDate: "2025-03-11",
    tags: ["Segurança"],
  },
  // DONE
  {
    id: "t9",
    projectId: "p3",
    title: "Definir paleta de cores",
    description: "Selecionar e documentar cores primárias e secundárias do rebranding",
    status: "done",
    priority: "medium",
    category: "Marketing",
    comments: 31,
    attachments: 6,
    daysLeft: 0,
    progress: 10,
    progressTotal: 10,
    members: [MEMBERS[1]],
    createdAt: "2025-01-10",
    dueDate: "2025-02-15",
    tags: ["Design"],
  },
  {
    id: "t10",
    projectId: "p1",
    title: "Estruturar organização das empresas",
    description: "Criar hierarquia e estrutura de dados para múltiplas empresas",
    status: "done",
    priority: "high",
    category: "Administrativo",
    comments: 14,
    attachments: 5,
    daysLeft: 0,
    progress: 20,
    progressTotal: 20,
    members: [MEMBERS[0], MEMBERS[2], MEMBERS[4]],
    createdAt: "2025-01-05",
    dueDate: "2025-02-01",
    tags: ["SaaS"],
  },
];
